security:
    encoders:
        App\Entity\Usuario: { algorithm: bcrypt , cost: 13 }

    role_hierarchy:
        ROLE_DIRECTIVO:  ROLE_USER
        ROLE_COORDINADOR:  ROLE_USER

    providers:
        usuarios:
            entity: { class: App:Usuario}

    firewalls:
        secured_area:
            pattern:    ^/*
            user_checker: App\Security\UserChecker
            form_login:
                login_path: index
                check_path: check
                default_target_path: index
                always_use_default_target_path: true
            logout:
                path:   logout
                target: index
                handlers: [app.logoutlistener]
            anonymous: ~
            remember_me:
                secret:  '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path: index

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/area, roles: ROLE_ADMIN }
        - { path: ^/arc/\d+/findbysubcapitulo, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/arc, roles: ROLE_ADMIN }
        - { path: ^/cargo/\d+/ajax, roles: [ROLE_ADMIN, ROLE_DIRECTIVO] }
        - { path: ^/cargo, roles: ROLE_ADMIN }
        - { path: ^/capitulo, roles: ROLE_ADMIN }
        - { path: ^/subcapitulo/\d+/findbycapitulo, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/subcapitulo, roles: ROLE_ADMIN }
        - { path: ^/grupo, roles: ROLE_USER }
        - { path: ^/notificacion, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/mensaje, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/usuario/\d+/edit, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/usuario/\d+/show, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/usuario, roles: [ROLE_ADMIN, ROLE_DIRECTIVO] }
        - { path: ^/plantrabajo, roles: ROLE_USER }
        - { path: ^/actividad, roles: ROLE_USER }
        - { path: ^/planmensualgeneral/\d+/edit, roles: ROLE_COORDINADOR }
        - { path: ^/planmensualgeneral/\d+/delete, roles: ROLE_COORDINADOR }
        - { path: ^/planmensualgeneral, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/actividadgeneral, roles: ROLE_COORDINADOR }
        - { path: ^/miembroconsejodireccion, roles: ROLE_COORDINADOR }
        - { path: ^/prueba, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: IS_AUTHENTICATED_FULLY }